# Generated by Django 4.1.3 on 2022-12-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_retievals_retieval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retieval',
            new_name='Retrieval',
        ),
    ]
